# Generated by Django 4.2.10 on 2024-03-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Age',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
