# Generated by Django 4.2.10 on 2024-03-08 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Friends_List',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
