# Generated by Django 4.2.10 on 2024-03-08 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
